spring:
  datasource:
    url: jdbc:mysql://database-1.cq7ffthx1phg.ap-northeast-2.rds.amazonaws.com/myapp?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: tjdls!2278
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    
    
  jpa:
    show-sql: true
    generate-ddl: true